"""auto update

Revision ID: 1e37b855c5d9
Revises: b5d9fe9cfe3d
Create Date: 2026-03-09 06:00:21.961992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e37b855c5d9'
down_revision: Union[str, Sequence[str], None] = 'b5d9fe9cfe3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('tool_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'tool_type')
    # ### end Alembic commands ###