"""auto update

Revision ID: 638934d4d995
Revises: 935197067403
Create Date: 2026-03-09 02:59:06.741567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638934d4d995'
down_revision: Union[str, Sequence[str], None] = '935197067403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('use_cases', sa.String(), nullable=True))
    op.add_column('tools', sa.Column('target_audience', sa.String(), nullable=True))
    op.add_column('tools', sa.Column('difficulty_score', sa.Integer(), nullable=True))
    op.add_column('tools', sa.Column('recommended_for', sa.String(), nullable=True))
    op.add_column('tools', sa.Column('popularity_score', sa.Integer(), nullable=True))
    op.add_column('tools', sa.Column('beginner_friendly', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'beginner_friendly')
    op.drop_column('tools', 'popularity_score')
    op.drop_column('tools', 'recommended_for')
    op.drop_column('tools', 'difficulty_score')
    op.drop_column('tools', 'target_audience')
    op.drop_column('tools', 'use_cases')
    # ### end Alembic commands ###