"""auto update

Revision ID: 6a04b431d666
Revises: 9a0a936537a6
Create Date: 2026-03-10 06:10:23.233552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a04b431d666'
down_revision: Union[str, Sequence[str], None] = '9a0a936537a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'skill_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'skill_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###