"""auto update

Revision ID: 9a0a936537a6
Revises: 1e37b855c5d9
Create Date: 2026-03-10 04:08:45.537229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a0a936537a6'
down_revision: Union[str, Sequence[str], None] = '1e37b855c5d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_queries', sa.Column('visitor_id', sa.String(), nullable=True))
    op.alter_column('user_queries', 'raw_query',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_queries', 'created_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('user_queries', 'skill_level')
    op.drop_column('user_queries', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_queries', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_queries', sa.Column('skill_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('user_queries', 'created_date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('user_queries', 'raw_query',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user_queries', 'visitor_id')
    # ### end Alembic commands ###