"""auto update

Revision ID: b5d9fe9cfe3d
Revises: 638934d4d995
Create Date: 2026-03-09 05:41:54.137029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d9fe9cfe3d'
down_revision: Union[str, Sequence[str], None] = '638934d4d995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('logo_url', sa.String(), nullable=True))
    op.alter_column('tools', 'short_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'short_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('tools', 'logo_url')
    # ### end Alembic commands ###